services:
  - type: web
    name: portleague
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portleague.wsgi:application --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: portleague.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 