# Generated by Django 5.0.4 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
