# Generated by Django 5.0.4 on 2025-04-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes', models.IntegerField(default=0)),
                ('avg_accuracy', models.FloatField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('hard_mode_completed', models.IntegerField(default=0)),
                ('normal_mode_completed', models.IntegerField(default=0)),
                ('achievement_level', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('master', 'Master')], default='novice', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Statistics',
            },
        ),
    ]
