# Generated by Django 5.0.4 on 2025-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(choices=[('history', 'Liga History'), ('stats', 'Statistics'), ('current', 'Current Season')], default='current', max_length=20),
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
