# Generated by Django 5.0.4 on 2025-04-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_quizattempt_questions_remove_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='category',
        ),
    ]
